### ISSUE TITLE
Deployment Workflow Docs

### ISSUE THREAD

**Issue by MikeiLL** [WPBP/WordPress-Plugin-Boilerplate-Powered#159]
Are you [still thinking](https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/issues/107) it would make sense to have some Documentation on how to deploy a plugin package?

Would you like me to [work on this](https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/wiki/How-to-do-a-plugin-package)?

I still use a slightly evolved version of [Eric Rallen](https://github.com/ericrallen/wp-base-plugin/blob/master/deploy.sh)s old bash script.

I also have a `zipFile.sh` script along the lines of [this one you had referenced](https://github.com/CodeAtCode/freemius-suite/blob/master/package.sh#L73).

Are these still basically the approaches you would recommend using/describing in docs?

**Comment by Mte90** [comment]
I migrated the docs to the website https://wpbp.github.io/wiki.html that is at https://github.com/WPBP/wpbp.github.io

Write how to deploy a package it is something that is missing indeed and I think that is better to explain how to do a zip-ready package because there is already WordPress docs about how to publish to svn repo https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/ and a lot of different script and services to publish on the repo.
Create another doc with that steps I think that can be confusing or a duplicate.

**Comment by MikeiLL** [comment]
I agree that a doc on how to deploy to zip and not subversion makes sense. Perhaps the Zip doc can include a link or two about WP svn repo deployment. Would you like me to write something up and PR it?

**Comment by Mte90** [comment]
Yes of course!
Can you do it on the website repository?

I am always looking on how to improve the docs, as I am the creator for me it is enough but probably a lot of things are not clear for everyone.

**Comment by MikeiLL** [comment]
> Yes of course!
> Can you do it on the website repository?
> 
You mean, like in https://github.com/WPBP/wpbp.github.io/tree/master/html/pages ?

**Comment by Mte90** [comment]
Yes exactly
