### ISSUE TITLE
[Feature] Our own CS

### ISSUE THREAD

**Issue by szepeviktor** [WPBP/WordPress-Plugin-Boilerplate-Powered#174]
```yaml
         run: "vendor/bin/phpcs -s --standard=CodeatCodingStandard --exclude=Squiz.PHP.CommentedOutCode,Generic.Commenting.Todo,SlevomatCodingStandard.Functions.UnusedParameter,SlevomatCodingStandard.Variables.UnusedVariable,Squiz.Commenting.FileComment ."
```

Why do we have a custom CS and exclude a part of it?
What do you think?

**Comment by szepeviktor** [comment]
When I've made my frankenstein `PSR12NeutronRuleset` it was tailor made for me :)

**Comment by Mte90** [comment]
I can explain very easily.
As it is a boilerplate there are a lot of examples in the code that are incomplete or code commented.
As they are fake positive because when someone generates the plugin with the generator and start develop this rules will be reported during the development but as boilerplate they are fake positive.
