### ISSUE TITLE
[Feature] Why not go full PSR-4?

### ISSUE THREAD

**Issue by szepeviktor** [WPBP/WordPress-Plugin-Boilerplate-Powered#176]
1. One `/src` directory for all classes, no exceptions
1. Subdirectories === Namespaces, e.g. `src/Engine/`
1. Abolish `backend/views/*`

**Comment by szepeviktor** [comment]
Abolish views -> go with `tag()`
https://github.com/szepeviktor/Toolkit4WP/blob/master/src/helpers.php#L17-L28

**Comment by szepeviktor** [comment]
Actually Timber is the final solution as WordPress has no templating engine.

**Comment by Mte90** [comment]
I personally don't like PSR-4 because "hide" all the files in a folder and also force folders with uppercase letters.
As this project when started was to be similar to wordpress also with file naming and other things and during the time evolved I tried to keep an hybrid solution.
In this way is familiar to newcomers, wordpress developers that need to learn new tools and so on.
Be full PSR-4 can be unfamiliar also because a lot of famous plugin doesn't do that.

**Comment by szepeviktor** [comment]
ok-ok

**Comment by Mte90** [comment]
I would like to migrate to timber because I don't like how views folder it is now but is something we can think about it.
