### ISSUE TITLE
[info] frontend and backend Enqueue.php script directions

### ISSUE THREAD

**Issue by kauaicreative** [WPBP/WordPress-Plugin-Boilerplate-Powered#228]
Fascinating project.
Do we have some instructions on how the backend enqueue system works? /assets/build/... is not being enqueued automatically. Furthermore the plugin's test settings page's tabs are not styles or functioning I assume because the assets are not being loaded. 
I would be grateful for some direction on how to use the frontend and backend Enqueue.php scripts.

**Comment by Mte90** [comment]
* https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/backend/Enqueue.php
* https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/frontend/Enqueue.php

Those are the 2 files that do that, if the file are not enqueue probably because the build folder is not generated? You need to run `npm build` otherwise the files are not there.

Did you used the https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered as this boilerplate alone does not work.

**Comment by kauaicreative** [comment]
Got it! Yes, I had built the assets but now see that I also needed to include the "inpsyde/assets" in the generator. It's working perfectly now - thanks!

**Comment by Mte90** [comment]
You are right as it is optional and if you remove it the code is removed in the boilerplate.

I think that I should improve somehow the generator or the documentation but I don't have idea for that (yet).

In the meantime I am closing it.

**Comment by kauaicreative** [comment]
It's an impressive undertaking, getting all of this working smoothly together. Bravo!

**Comment by Mte90** [comment]
It is a long time project :-)
